export const NutritionChartNames = {
  macro: {
    names: [
      // "Water",
      "Protein",
      "Lipids",
      "Fatty acids, total monounsaturated",
      "Fatty acids, total polyunsaturated",
      "Fatty acids, total saturated",
      "Fatty acids, total trans",
      "Carbohydrates",
      "Carbohydrate, by difference",
      "Carbohydrate, by summation",
      "Carbohydrate, other",
      "Sugars, Total",
      "Sugars, added",
      "Cholesterol",
      "Fiber, soluble",
      "Fiber, insoluble",
      "Fiber, total dietary",
      // "Soluble dietary fiber (SDFP+SDFS)",
      // "Insoluble dietary fiber (IDF)",
      // "Ash",
      // "Energy",
    ],
  },
  micro: {
    minerals: {
      names: [
        "Iron, Fe",
        "Iron, heme",
        "Iron, non-heme",
        "Potassium, K",
        "Copper, Cu",
        "Magnesium, Mg",
        "Calcium, Ca",
        "Fluoride, F",
        "Phosphorus, P",
        "Sodium, Na",
        "Sulfur, S",
        "Zinc, Zn",
      ],
    },
    vitamins: {
      names: [
        "Vitamin A, RAE",
        "Vitamin A, RE",
        "Vitamin B-12",
        "Vitamin B-6",
        "Vitamin C, total ascorbic acid",
        "Vitamin C, added",
        "Vitamin D (D2 + D3), International Units",
        "Vitamin D4",
        "Vitamin E",
        "Vitamin E, added",
        // "Vitamin E (label entry primarily)",
        "Vitamin K (Dihydrophylloquinone)",
        "Vitamin K (phylloquinone)",
        "Vitamin K (Menaquinone-4)",
        "Vitamins and Other Components", // ?
        "Riboflavin",
        "Riboflavin, intrinsic",
        "Folate, total",
        "Niacin",
        "Thiamin",
        "Thiamin, added",
        "Flavonoids, total",
        "Leucine", // amino acid
        "Lycopene", // phytochemical from tomatoes
      ],
    },
  },
  other: {
    names: [
      "Silicon, Si",
      "Other carotenoids",
      "Lactic acid",
      "Sorbitol",
      "Polyphenols, total",
      "Zeaxanthin",
      "Nitrates",
      "Citric Acid",
      "Carotene, alpha",
      "Carotene, beta",
      "Carotene",
      "Caffeine",
      "Fructose",
      "Galactose",
      "Glucose",
      "Lead, Pb",
      "Total sugar alcohols",
    ],
  },
};
